### ISSUE TITLE
"trial_ends_after_show_end_time" parameter

### ISSUE THREAD

**Issue by enrytusini** [kurokida/jspsych-psychophysics#10]
I'm looking for a way to end a trial when "show_end_time" is reached.
It's appropriate to use the parameter "trial_duration" (trial_duration=show_end_time)? 
Or if the onset of the visual stimulus lags some ms it will be cut off by the end of the trial("trial_duration")?

**Comment by kurokida** [comment]
Thank you for using my plugin!

I haven't looked into it in detail, but it is expected that the trial will end when the trial_duration time is reached. As a result, it is possible that the presentation time of the stimulus would be shorter, but I think that the time would be a very small.

Please see the Result1 of this page:
https://osf.io/pj4sb/wiki/Accuracy%20test%20December%202020/

You'll see the measured SOAs were accurate in almost all cases. Given the result, visual stimuli are expected to be presented at intended times.
