### ISSUE TITLE
text positioning

### ISSUE THREAD

**Issue by giuconte** [kurokida/jspsych-psychophysics#11]
when setting the text position, if I try to move the text vertically the parameter startY:200, only works if I also provide  startX:0,
If  startX is omitted, then startY:200, doesn't work anymore

**Comment by kurokida** [comment]
Thank you for using my plugin!
Could you show me the source code or the experimental web page?

**Comment by giuconte** [comment]
thank you for developing such a great plug-in.
sorry for bothering you, I have figured out an error on my side.
Giulio Contemori

PhD in* Neuropsychology*
orcid.org/0000-0002-1873-1472
italian phone +39 3281086839
french phone +33 0768420399


Il giorno mer 30 dic 2020 alle ore 06:20 Daiichiro Kuroki <
notifications@github.com> ha scritto:
