### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by giuconte** [kurokida/jspsych-psychophysics#12]
when using the jspsych-resize prior to use the jspsych-psychophysics if the resize is a little too big scrollbars are automatically activated.
Using document.body.classList.add("stop-scrolling"); doesn't prevent the appearance of the scrollbars. Would be better to disable them by default?

**Comment by kurokida** [comment]
I'm not sure whether I understand your problem or not.
But, the bellow code might be useful. The number of 10 is arbitrary.

```javascript

canvas_height:  window.innerHeight - 10,

```

**Comment by giuconte** [comment]
Thank you for your very fast reply.
This piece of code might come in handy in the future.
Here the link to my demo

   -
   http://147.162.143.143:9000/publix/182/start?batchId=185&generalMultiple

the instructions are in Italian (sorry for this). If you try to resize the
box just a little bit larger then the actual credit card next you will see
the scroll bar appearing
after disabling the scrolling bars with
document.body.classList.add("stop-scrolling");
the bars are not showing for all the jspsych plug-ins except the the
jspsychophysics.
resize has been achieved with jspsych-resize.js
Giulio Contemori

PhD in* Neuropsychology*
orcid.org/0000-0002-1873-1472
italian phone +39 3281086839
french phone +33 0768420399


Il giorno mer 30 dic 2020 alle ore 06:25 Daiichiro Kuroki <
notifications@github.com> ha scritto:

**Comment by lawero** [comment]
add this to your css for the class "stop-scrolling"
```
overflow-x: hidden;
overflow-y: hidden !important;
```

The problem is that `document.body.classList.add("stop-scrolling")` just adds a class called "stop-scrolling" to the body element. But looking your css there is no properties for this class. 
`!important` is not very recommended but it allows to overwrite the "overflow-y: hidden" inside jspsych.css (or you can just delete it but I don't know what else is used for)

**Comment by giuconte** [comment]
Thank you very much!!

I understood your suggestion and it's perfect.
I'm using your plug-in for more then one experiment. I will be sure to cite
you work.

Thank you,
Giulio.

Il ven 1 gen 2021, 23:55 lawero <notifications@github.com> ha scritto:

**Comment by kurokida** [comment]
Thanks @lawero for replying instead of me.
@giuconte , @lawero is not the same person as me (@kurokida )

Thank you very much for using my plugin!
