### ISSUE TITLE
Meaning of avg_frame_rate

### ISSUE THREAD

**Issue by lawero** [kurokida/jspsych-psychophysics#13]
The frame rate for a 60Hz monitor is about 16.6s. What does mean when the avg_frame_rate is about (for example) 20ms?

**Comment by kurokida** [comment]
Thank you for using my plugin!
I apologize for the delay in responding.

The avg_frame_time is calculated as follows.

elapsed_time = the time when the requestAnimationFrame was last called - the time when the requestAnimationFrame was first called

avg_frame_time = elapsed_time / the number of times the requestAnimationFrame was called.

For example, if the elapsed time is longer for some reason, the avg_frame_time will also be longer than the theoretical value

Is this answer sufficient?

**Comment by lawero** [comment]
yes, thanks! :D
