### ISSUE TITLE
Screen pixel

### ISSUE THREAD

**Issue by hkPark742** [kurokida/jspsych-psychophysics#18]
Hello!

I'm using Mac Pro 13.3-inch with 2560x1600 and I've set canvas width as 1600px. Even though 1600px smaller than screen resolution, it wouldn't fit into my screen. I've heard somewhere that it is because pixels are too small on Mac (https://github.com/jspsych/jsPsych/discussions/1030). I also need to record the position of mouse click. Is there any way I can fit 1600px canvas into a screen using the actual resolution of my screen?

**Comment by kurokida** [comment]
Thank you for using my plugin!

Unfortunately, I won't be able to use Mac to check it out any time soon.

First, please extract the attached zip file and run resolution.html.
You'll see the actual width and height of the canvas fitted to the window.
Using those values as a reference, you can determine the width and height of the canvas.

Maybe, the resolution.html will show resolution less than 2560x1600 even if the window is full size.
[test0128.zip](https://github.com/kurokida/jspsych-psychophysics/files/5884335/test0128.zip)

**Comment by hkPark742** [comment]
Thank you! It helped me a lot.
