### ISSUE TITLE
HTML buttons and psychophysics

### ISSUE THREAD

**Issue by Antoinette33** [kurokida/jspsych-psychophysics#19]
Hello,
I was wondering if I could also use HTML buttons along with psychophysics within a trial? I'm using the HTML buttons with pictures on them as I'm making a study designed for children. I would like to use your plug-in so that images and sound would play at the same time during a trial (as if someone is reading them a story book) and then children can respond by clicking the buttons.

Any help would be greatly appreciated,
Antoinette Dawn Trott :)

**Comment by kurokida** [comment]
Thank you for using my plugin!

Please see https://jspsychophysics.hes.kyushu-u.ac.jp/pluginParams.html
You can specify the response_type property as 'button'.
Also please see the explanation of parameters related to a button response.

If the problem persists, please contact me again.

**Comment by Antoinette33** [comment]
Hello,
Thanks for responding. I am still confused on how to use this. Could you please send me an example or explanation on how to use it?

Thanks,
Antoinette

**Comment by kurokida** [comment]
Here is [the sample program](https://www.hes.kyushu-u.ac.jp/~kurokid/jspsychophysics/demos/mouse_event.html) which records a response using buttons.

Then, here is the code:

```javascript

const trial = {
          type: 'psychophysics',
          canvas_height: 500,
          button_choices: ['YES', 'NO'],
          prompt: '<p>Click and move the mouse.</p>',
          stimuli: [circle_obj, line_obj], // These can be referenced using the jsPsych.currentTrial().stim_array array.
          response_type: 'button',
          vert_button_margin: '50px',
          horiz_button_margin: '50px',
}
```
