### ISSUE TITLE
"The experiment failed to load."  in twoSoundsWithSOA.html

### ISSUE THREAD

**Issue by masaii1224** [kurokida/jspsych-psychophysics#2]
Hi, thank you for the nice project.

In my environment(macOS Catalina version 10.15.6, Mac Mini(2018), Chrome Version 84.0.4147.105 (Official Build) (64-bit)), the demo of twoSoundsWithSOA.html did not work correctly with the error of "The experiment failed to load."

and this error is fixed when I added 

use_webaudio: false,

 in jsPsych.init().

**Comment by kurokida** [comment]
Thank you for your message.
Perhaps you are not running this demo program on the server, but on your local computer?

You should upload the files to a web server to use the WebAudio.
This is mentioned at the jsPsych forum:
https://groups.google.com/forum/#!msg/jspsych/eth7QtLghvY/DR8Hx7CADwAJ

And, you should turn on the WebAudio for accurate presentation of audio stimuli.
