### ISSUE TITLE
Integrating gaborgen-js with jspsych-psychophysics

### ISSUE THREAD

**Issue by giuconte** [kurokida/jspsych-psychophysics#20]
Hello,
I tried to use to gaborgen-js with jspsych-psychophysics. I can easily use gaborgen-js with the basic jspsych plug-ins for example with img src= gaborgen(50, 50)  as a HTML stimulus. 
I didn't find an easy way with jspsych-psychophysics, I tried to draw directly the matrix with obj_type: 'manual' but since I got stuck I was wondering if there was an easier way. Do you have any suggestions?
Thank you again for your great work.
Best,
Giulio.

**Comment by kurokida** [comment]
Hi @giuconte ,

I was also just trying to integrate gaborgen-js into the psychophysics plugin.
It's not complete, but I've published it as a new branch named as **gabor**.

Please change the branch to gabor and download it.

You'll see the demos/draw-gabor.html and demos/draw-multi-gabor.html

Currently, the tilt, sf, and phase properties are easy to set. For other properties, please change gab.js directly.

I am noticing one minor problem, the background color of the gabor patch depends on the value of the property. See the demos/draw-multi-gabor.html.

Best regards,

**Comment by giuconte** [comment]
that's a very nice feature you are adding!!
I'll try setting the properties, but I will also look at the gab.js itself.
Luckily I asked, no need to reinvent the wheel 👍 
Thank you very much.
Giulio.

**Comment by kurokida** [comment]
@giuconte , now my plugin officially supported [the presentation of gabor patches](https://jspsychophysics.hes.kyushu-u.ac.jp/gabor.html). Please be careful that the gaborgen-js is not used, although I have referenced it.

**Comment by giuconte** [comment]
This is neat!
I have already tried it and it runs smoothly.
than you very much.

Giulio Contemori

PhD in* Neuropsychology*
orcid.org/0000-0002-1873-1472
italian phone +39 3281086839
french phone +33 0768420399


Il giorno gio 18 feb 2021 alle ore 06:14 Daiichiro Kuroki <
notifications@github.com> ha scritto:
