### ISSUE TITLE
timing in frames in different obj_type

### ISSUE THREAD

**Issue by sacchilvia** [kurokida/jspsych-psychophysics#21]
Hi!
I am setting the presentation timing of visual stimuli (i.e. obj_type: circle) using show_start_frame and show_end_frame. I also would like to present auditory stimuli (i.e. obj_type: ‘sound’), but in this case it seems that I can set the presentation timing only using show_start_time and show_end_time. 
Thus I was wondering if having some stimuli with the timing set in frames and other stimuli with the timing set in ms could negatively influence their synchronization. Which do you think would be the best option to have synchronized visual and auditory stimuli?
Thanks a lot in advanced!
Silvia

**Comment by kurokida** [comment]
Thank you for using my plugin！
Do you use the latest plugin? Probably you can specify the show_start_frame property for the sound object as well as the circle object.
Note that you must also specify the is_frame property as true. 
If the problem remains, please show me the code.

However, there's a more serious issue.
Previous research including [mine](https://rdcu.be/b5Nie) showed that the SOA between visual and audio stimuli was not accurate.
[In my resent observation](https://osf.io/pj4sb/wiki/Accuracy%20test%20December%202020/), this problem remains.
So, you should use audio and visual stimuli in online experiments with caution.
