### ISSUE TITLE
Sound & Image & Webgazer experiment

### ISSUE THREAD

**Issue by cainesap** [kurokida/jspsych-psychophysics#22]
Hello,

Thank you for making this plug-in available. It's extremely helpful for sound & image experiments with jsPsych.
I hope to also make use of webgazer for eye-tracking, which has been added as an extension in [release 6.3](https://github.com/jspsych/jsPsych/issues/1296)

To make use of the webgazer extension I need to call the jspsych.js file from the main repository. Which then I think means that some jspsych-psychophysics functions become broken. So for instance image display is fine, but audio play is not. I get the error message: "this.audio.play is not a function"

Your demo `twoSoundsWithSOA.html` still works fine for me, which is why I think it's the change of `jspsych.js` file which causes the problem. Does that sound right to you? If so, do you think there's something I can do about it?

many thanks in advance, Andrew

**Comment by kurokida** [comment]
Thank you for using my plugin!

I'm sorry to say this, but I have not yet checked that my plugin works propery with the webgazer extension.

Could you show me the code where the error is occurring?

Also, I have one concern.

Even if I can eliminate the error, because of the high load, my plugin (or jsPsych) may not be able to present the stimulus at the exact time you intend with the webgazer extension. Please keep that in mind.

**Comment by cainesap** [comment]
No need to apologise! The extension is still very new :)

Do you mean my code or your code? In your code it's line 841 and the command `this.audio.play();`
But I guess you mean you want to see my code?

Thank you for the point about high load, that is important too and something I will watch closely.

best, Andrew

**Comment by kurokida** [comment]
Thank you for your reply.

I understood the issue. 
I attach the latest psychophysics plugin file which has not yet been uploaded in my repository.
Please download and change the file extension from txt to js.
Then, replace the file, and check the issue is removed or not?

By the way, I ran the example code of the webgazer which was included in the jsPsych library.
[jspsych-psychophysics.txt](https://github.com/kurokida/jspsych-psychophysics/files/6034798/jspsych-psychophysics.txt)

There were no errors, but it didn't seem to be recording eye movements very accurately.

**Comment by cainesap** [comment]
Thank you so much for your help!

I downloaded the file, changed the extension, but I'm sorry to say that the problem continues. This time the error message is a little different:

```
Uncaught TypeError: Cannot read property 'start' of undefined
    at audio_stimulus.play (jspsych-psychophysics.js:847)
    at step (jspsych-psychophysics.js:1075)
```

It refers to line 847 which is `this.audio.start(this.context.currentTime);`

Do you know why this should be, or if there's more information I can share please let me know?
best, Andrew

**Comment by kurokida** [comment]
Thank you for your feedback.

Did this error occur when running my sample program, or yours?
If when running your program, could you show me the code?

**Comment by cainesap** [comment]
Thank you, and sorry I should have explained that.

When I run `twoSoundsWithSOA.html` I see the following 2 errors (with the new js file you shared, no errors with the old one):

```
Uncaught TypeError: jsPsych.pluginAPI.getAudioBuffer(...).then is not a function
    at new audio_stimulus (jspsych-psychophysics.js:816)
    at Object.jsPsych.plugins.psychophysics.plugin.trial (jspsych-psychophysics.js:1015)
    at doTrial (jspsych.js:889)
    at nextTrial (jspsych.js:857)
    at Object.window.jsPsych.core.finishTrial (jspsych.js:294)
    at end_trial (jspsych-html-button-response.js:168)
    at after_response (jspsych-html-button-response.js:147)
    at HTMLDivElement.<anonymous> (jspsych-html-button-response.js:116)
```

And:

```
Uncaught ReferenceError: Cannot access 'response' before initialization
    at Object.after_response [as callback_function] (jspsych-psychophysics.js:1200)
    at Object.listener_function [as fn] (jspsych.js:2136)
    at HTMLBodyElement.root_keydown_listener (jspsych.js:2044)
```

Btw,  I commented out line 17 because of this error I wasn't sure how to fix:

```
Uncaught TypeError: jsPsych.version is not a function
    at jspsych-psychophysics.js:17
    at jspsych-psychophysics.js:1232
```

The error message I shared in my previous message happens with my own program. I'll share the code for that but first let you respond to this current message to see what you think is happening.

best, Andrew

**Comment by kurokida** [comment]
Thank you for the explanation.

Now, you can see [the compatible version of my plugin](https://github.com/kurokida/jspsych-psychophysics/tree/compatible_wit_jspsych_6_3_0), although it is same as the file I gave you yesterday.

I checked that [the twoSoundsWithSOA.html works properly](https://www.hes.kyushu-u.ac.jp/~kurokid/jsPsychophysics-compatible/demos/twoSoundsWithSOA.html).
But, this demo file was also updated for the jsPsych 6.3.0.
Specifically, I changed the preload section.
Could you see the difference between the old twoSoundsWithSOA.html and the latest twoSoundsWithSOA.html?

I think your program should be updated using the new way to preload the audio files.

See also [the Media Preloading page](https://www.jspsych.org/overview/media-preloading/).

**Comment by cainesap** [comment]
Thank you very much! I see what you mean about the difference in preloading now. My program works with these changes, thank you again for your time and help :))

**Comment by kurokida** [comment]
I'm glad I could be of help.

**Comment by cainesap** [comment]
Hello,
I believe that your [branch for jsPsych 6.3.0](https://github.com/kurokida/jspsych-psychophysics/tree/compatible_wit_jspsych_6_3_0) is still fine with the new release 6.3.1 , from a test run of my app. But please let me know if you think it might break for any reason?
many thanks again for your help, Andrew

**Comment by kurokida** [comment]
Dear Andrew,

I haven't checked it in detail, but from [the release note](https://github.com/jspsych/jsPsych/releases/tag/v6.3.1), I think it will work fine.
Then I recommend you to use [the latest plugin](https://github.com/kurokida/jspsych-psychophysics/releases), not the one from that branch.

Best regards,
Daiichiro

**Comment by cainesap** [comment]
Thank you very much Daiichiro, I will do that.
best wishes, Andrew
