### ISSUE TITLE
Image Padding from Center?

### ISSUE THREAD

**Issue by rsdrake** [kurokida/jspsych-psychophysics#23]
Thank you for your excellent plugin, Kuroki-san.

I'm trying to display two images side by side and centered on the screen. To prevent overlap, I have imagined that I would need to generate the two images at the center of the screen, plus or minus a number of pixels. It seems I could do this by setting startX to the result of a function like the following:

```
startX: function() {
return jsPsych.currentTrial().centerX - 200
}
```

However, whenever I try to modify centerX as shown above, the image fails to load entirely. I'm a bit confused, because if I run the following code in my browser console during the image response part of my experiment, I can get the number I expect:

`offset = jsPsych.currentTrial().centerX - 100`

I'm only a novice in javascript, so it's quite possible I'm making a silly mistake. I would greatly appreciate any advice on how to get the images to display as I am intending.

**Comment by kurokida** [comment]
Thank you for using my plugin!

I'm sorry, but you can't specify a function as the startX property.
Probably, the following code works well.
By setting origin_center to true, you can specify the coordinates relative to the screen center.
Please use the latest version of jsPsych and my plugin.

```javascript

    const images = [ // All the images used in this demo
        './img/scissors.png',
        './img/pen.png',
    ];

    // Preloading files are needed to present the stimuli accurately.
    const preload = {
        type: 'preload',
        images: images,
    }


    const trial = {
        type: 'psychophysics',
        stimuli: [
            {
                obj_type: 'image',
                file: images[0],
                startX: -200,
                origin_center: true
            },
            {
                obj_type: 'image',
                file: images[1],
                startX: 200,
                origin_center: true
            }
        ],
    }

    jsPsych.init({
        timeline: [preload, trial],
        on_finish: function(){jsPsych.data.displayData();}
    });

```

**Comment by rsdrake** [comment]
This is a perfect solution. Thank you so much for the code!

Take care.
