### ISSUE TITLE
How to record record the simultaneous pressing of two keys as response?

### ISSUE THREAD

**Issue by giuconte** [kurokida/jspsych-psychophysics#24]
Hello,
first of all, thank you for sharing your wonderful work.
Would it be possible to record a simultaneous pressing of two keys (key combination)?
For example, I would like to have 3 possible answers to a trial:
left arrow, right arrow, both arrows simultaneously. Is there a way?

**Comment by kurokida** [comment]
Thank you for using my plugin.

For multiple keystrokes in the same trial, please see [this demo](https://www.hes.kyushu-u.ac.jp/~kurokid/jspsychophysics/demos/keyboard_event.html).

But perhaps this demo is a little different from what you are looking for.

[This page](https://teratail.com/questions/38689
) may be useful to you. 
Sorry for this page is written in Japanese, but the code may be useful.

Also, please refer to [Parameters related to event handlers](https://jspsychophysics.hes.kyushu-u.ac.jp/pluginParams/#parameters-related-to-event-handlers).

My plugin can't offer you a direct solution, but I think you can probably solve the problem by writing the code manually.

**Comment by giuconte** [comment]
Wonderful suggestion, the link was helpful.
Solved.
Thank you very much.
Giulio.
