### ISSUE TITLE
compatible_with_jspsych_7.0?

### ISSUE THREAD

**Issue by kiante-fernandez** [kurokida/jspsych-psychophysics#26]
Is the psychophysic plugin compatible with jspsych 7.0? Are their plans to make the adjustments?

**Comment by kurokida** [comment]
Thank you for using my plugin!

I'm sorry,  my plugin does not yet support jsPsych v7. I am preparing it now, but it will probably take a month.

**Comment by kurokida** [comment]
The psychophysics plugin is now compatible with jsPsych V7. Sorry to keep you waiting.
You can download it from
https://github.com/kurokida/jspsych-psychophysics/releases/tag/v3.0.0
