### ISSUE TITLE
event handlers compatible with gabor parameters

### ISSUE THREAD

**Issue by rouderj** [kurokida/jspsych-psychophysics#27]
Hi, I can change certain gabor parameters with the event handler examples, for startX, but I cannot change others, such as tilt.  for example, jsPsych.currentTrial().stim_array[0].startX = 50 changes the position as expected.  jsPsych.currentTrial().stim_array[0].tilt=50 does not change the tilt.  any thoughts?  much thanks.   

This example should change both tilt and startX, but it only shifts the gabor and does not change the tilt :(

   let current = 90;

      var circle_obj = {
        obj_type: 'gabor',
        startX: current,
        startY: 150,
        tilt: current,
        sf: 0.05,
        phase: 90,
        width: 150,
        sc: 10,
        contrast: 0.5,
        disableNorm: true
      };

      const trial = {
          type: 'psychophysics',
          canvas_height: 500,
          prompt: '<p>Pressing the ArrowUp/ArrowDown key, the color of the circle will change. <br>Press the space key to finish the program.</p>',
          stimuli: [circle_obj], // These can be referenced using the jsPsych.currentTrial().stimuli array.
          response_type: 'key',
          choices: [' '],
          key_down_func: function(event){ // The key_up_func is also available. In that case, the color of the circle changes when you release the key. 
            if (event.key === 'ArrowUp'){
              current += 2;
            } else if (event.key === 'ArrowDown'){
              current -= 2;
            }

            // Note that when specify the space bar, you need to write event.key === ' ' not event.key === 'space'.
            
            jsPsych.currentTrial().stim_array[0].startX = current;
            jsPsych.currentTrial().stim_array[0].tilt = current;
          },
      }

**Comment by kurokida** [comment]
Thank you for using my plugin!
I am very sorry for the delay in replying.

I think that the following code is probably close to the program you want.

```javascript
    const nTrials = 20
    let trial_num = 1
    let current = 90;

    const trial = {
        type: 'psychophysics',
        canvas_height: 500,
        prompt: '<p>Press the ArrowUp/ArrowDown key to change the position and tilt of the gabor.</p>',
        stimuli: function(){
          const gabor_obj = {
              obj_type: 'gabor',
              startX: current,
              startY: 150,
              tilt: current,
              sf: 0.05,
              phase: 90,
              width: 150,
              sc: 10,
              contrast: 0.5,
              disableNorm: true
          };

          return [gabor_obj]
        },
        response_type: 'key',
        choices: [' ', 'ArrowUp', 'ArrowDown'],
    }

    const loop_node = {
        timeline: [trial],
        loop_function: function(data){
            if (trial_num < nTrials){
                trial_num++

                if (data.values()[0].response === 'arrowup'){
                  current += 2
                } else { // arrowdown
                  current -= 2
                }

                return true
            } else {
                return false
            }
        }
    }

    /* start the experiment */
    jsPsych.init({
        timeline: [loop_node],
        on_finish: function(){jsPsych.data.displayData();}
    });
```

Please see [the looping timelines](https://www.jspsych.org/6.3/overview/timeline/#looping-timelines) and [the dynamic parameters](https://www.jspsych.org/6.3/overview/dynamic-parameters/), and note that my plugin is not compatible with jsPsych V7.

**Comment by rouderj** [comment]
Thank you very much!  I am going to learn loop_function which is new to me.
