### ISSUE TITLE
Simulation mode for psychophysics

### ISSUE THREAD

**Issue by nikbpetrov** [kurokida/jspsych-psychophysics#28]
Hi,

Thanks a lot for developing this plugin! Upon examination, it looks like it's quite well-developed and takes advantage of some powerful new tools to allow quite solid precision in timing online experiments. I think it could cast serious concerns for the conclusions regarding timing on some relatively recent (but already dated) online timing experiments (e.g. [here](https://peerj.com/articles/9414/) or [here](https://link.springer.com/article/10.3758/s13428-020-01501-5)).

Anyhow, I was wondering if there are any plans in the pipeline to update the plugin with a simulation mode as have other jsPsych plugins - see [here](https://www.jspsych.org/7.1/overview/simulation/). In any case, I need to develop that at least for myself so if you have any comments/suggestions/feedback or are already working/have thought about this, I would genuinely appreciate your feedback.

Thanks in advance!

**Comment by kurokida** [comment]
Thank you for your valuable comments!

I know about the simulation mode, but at the moment I have no plans to incorporate it.
I'm currently working on integrating [PixiJS](https://pixijs.com/) into the psychophysics plugin.
It will probably take about a month to complete this task.
After that is done, I may incorporate a simulation mode.

Best, Daiichiro
