### ISSUE TITLE
Prolem with object 'sound'

### ISSUE THREAD

**Issue by miguelo93** [kurokida/jspsych-psychophysics#34]
Hi,

I'm having trouble with the plug-in. It failed loading audio files with a message saying `Try checking the file path..` I have last version of the plugin plus the JsPsych version which come on github. the probelm boils down when the plugin calls :  jsPsych.pluginAPI.getAudioBuffer(this.file).

If I use a JsPych plugin as jsPsychAudioKeyboardResponse this function give me something like : ` Promise { <state>: "fulfilled", <value>: AudioBuffer }`
When I use the same audio file in the psychophysics plugin I get  :` Promise { <state>: "fulfilled", <value>: "tmp" }`.

What can be the issue ?  I've tried both offline and online (Pavlovia).

Thank you.

**Comment by kurokida** [comment]
You seem to have close this issue right after you opened it. Did you solve the issue by yourself?
