### ISSUE TITLE
slider response

### ISSUE THREAD

**Issue by franfrutos** [kurokida/jspsych-psychophysics#35]
Hi!

I've been reading about jsPsych and this plugin reciently. I don't know much about web development and jsPsych yet, but I wonder if this plugin could be extended to support the use of sliders. And maybe to use the slider to dynamically change a stimulus on screen.

**Comment by kurokida** [comment]
Thank you for contacting me.
Unfortunately, my plugin does not provide integration with sliders.
Have you already asked your question on [the official jsPsych forum](https://github.com/jspsych/jsPsych/discussions)?
