### ISSUE TITLE
Concurrent presentation of images and sounds

### ISSUE THREAD

**Issue by marco2gandolfo** [kurokida/jspsych-psychophysics#43]
Thanks for this wonderful toolbox!

I am using jsPsych 6.3.1 alongside jspsychophysics 2.3.4 to present images together with sounds. Particularly, the sound stays on as long as an image (2 seconds) on screen. After that, a mask and a probe image follow.
Everything works well on a local server, but when I push my experiment online on pavlovia I get the following error:

![image](https://user-images.githubusercontent.com/43584866/233981138-06e8c878-42e6-429d-9fd0-ea45042919cb.png)

It is worth noting that this error occurs randomly, causing the image concurrent to the sound to freeze. Also, this error does not always occur, in some cases the script runs just fine ! This led me to think that may be something on the server side (pavlovia), but I thought I'd ask here as well.

I am not sure I fully understand the nature of this error. On my side I tried several times to change the audio files (thinking that those I was using were somewhat corrupted), to compress them from wav to mp3, and to rename them. But it seems it does not relate to my coding.

Thanks for any help you could provide.

**Comment by kurokida** [comment]
Thank you for using my plugin!

Can I access the program page? Could you show me the URL?

Or, do you have an idea to upgrade the latest ones of jsPsych and my plugin?

**Comment by marco2gandolfo** [comment]
Dear Daiichiro, 
Thanks a lot for your reply!

[This is the URL for the study]( https://run.pavlovia.org/m.gandolfo/soundscape_extension_1/?env=1 )

I considered updating many times, but I would have a lot of code to rewrite and I never _had to_ do it so far, perhaps is a good time to do so. Do you think that would improve the audio - image concurrent presentation?

My thoughts about this were that it might be a strange interaction with the server being slow in the last few weeks, however the audio files are all preloaded, so I don't see why they should freeze because of the server (pavlovia) being slower than usual.

Thanks again.

**Comment by marco2gandolfo** [comment]
Dear @kurokida 
Thanks a lot, I will definitely upgrade for the next work.
I tried to set the use_webaudio property to false and now everything works. In my case, where the image is presented for seconds, timing does not seem to be an issue (at least qualitatively speaking).

Thanks again for your help and for the info - very helpful!

Cheers,
Marco
