### ISSUE TITLE
Pre-load stimuli

### ISSUE THREAD

**Issue by keijiota** [kurokida/jspsych-psychophysics#44]
Hello, I just posted the same enquiry to JsPsych Github page but let me ask the same question here. 

I think a normal protocol to load stimuli is to give a path to stimuli which are stored in a local machine. I just wonder if there is any approach to load stimuli which are stored in the website (as if we download packages on Github from command window) or some other local machine using IP address. The problem is that we want to keep our stimuli of image files in some place other than a local PC (which is actually data security system in our institution) and get access to there by some way. 
Thanks as always. 

Keiji

**Comment by kurokida** [comment]
ご質問、ありがとうございます。英語でご質問いただきましたが、意思疎通を円滑にするため日本語で回答させていただきます。英語での議論は、本家jsPsychのほうでなされるかと思いますので。

実はまだ、ご質問の内容を正確に把握できておりません。私の経験を回答しますと、ウェブサーバーに実験プログラム（htmlファイルやjsファイル）を設置し、それと同じ場所に画像も設置しています。それで問題なく読み込めています。この場合、画像を参照するパスは、相対パスで指定できるので、特に問題はありません。

何らかの理由で、実験プログラムと画像を別のウェブサーバーに保存する必要があるということでしょうか？
例えばですが、
https://codepen.io/kurokida/pen/OJgMZRd
のコードなどは参考にならないでしょうか？
このコードでは、別サーバーにある画像を参照（プリロード）しています。

もし私がご質問内容を勘違いしているときは、追加でご説明をお願いできますと幸いです。
どうぞよろしくお願いいたします。

**Comment by keijiota** [comment]
いつもお世話になっております。ご回答ありがとうございます。またコードの参考例をありがとうございます。理解できました。
その通りです。実験プログラムと画像を別のウェブサーバーに保存する必要があります。今回は顔刺激を使うので個人情報の管理のため、大学のセキュリティシステム内に画像を置いておきたいのですが、外部からアクセスすることが難しそうなので、この方法は諦めた方がよさそうです。
ご丁寧に解説頂き大変ありがとうございました。

**Comment by kurokida** [comment]
お返事をありがとうございました。

本家jsPsychのDiscussionはこちらですね。今後のために一応リンクをつけておきます。
https://github.com/jspsych/jsPsych/discussions/3139
私の回答と似たものでしたね。

刺激画像がデリケートなものの場合は、やはりオンライン実験は避けたほうがよいように感じます。
AIなどを使って架空の人物画像を使うなどが代替案としてはあるかもしれません。
