### ISSUE TITLE
trouble importing npm plugin

### ISSUE THREAD

**Issue by LeslieHeld** [kurokida/jspsych-psychophysics#46]
Hello!

Thank you for the psycho-physics plugin on npm, I have followed the according closed github issue.

I am also using JsPsych Builder and I have tried to install the plugin (via https://www.npmjs.com/package/@kurokida/jspsych-psychophysics?activeTab=code) but I am facing issues with the import. When trying to install it, it only creates a "config" folder in my node-modules folder but there is no jspsych-psychophysics plugin.

I was wondering if anyone has faced and solved a similar issue?

Thanks in advance!

**Comment by kurokida** [comment]
Hi, thank you for using my plugin!

After reading your post, I tried to make an simple program using both the builder and psychophysics plugin, and then I did it successfully. So, I'm not sure what happened in your environment.

I added a brief explanation for the builder users. Could you see [the expnation](https://github.com/kurokida/jspsych-psychophysics) and try it again?

**Comment by LeslieHeld** [comment]
Thank you so much for your quick reply and for adding the explanation. Indeed, creating a new test experiment and starting from the psychophysics installation did the trick! Must have been some dependency issue in the previous experiment, I should have thought of that...

**Comment by kurokida** [comment]
Thank you for your reply. If the problem remains, I recommend you to ask questions on the builder's repository. I close this topic once, but please don't hesitate to contact with me.

**Comment by kurokida** [comment]
Thank you for your reply. If the problem remains, I recommend you to ask questions on the builder's repository. I close this topic once, but please don't hesitate to contact with me.
