### ISSUE TITLE
Making text stimuli bold and coloured

### ISSUE THREAD

**Issue by keijiota** [kurokida/jspsych-psychophysics#47]
Hello, hope you are well. 
I just wonder whether we can make some parts of the text bold and colored while leaving other parts of the text. I tried the following code, which did not work out. 

![image](https://github.com/kurokida/jspsych-psychophysics/assets/36744375/cbdca57a-d35f-46b3-bb37-20f6681293c9)

![Screenshot 2023-11-29 081826](https://github.com/kurokida/jspsych-psychophysics/assets/36744375/7e4dc018-9c71-45fd-931b-f8ac913ef027)

Many thanks in advance for your suggestions. 

Best,
Keiji

**Comment by kurokida** [comment]
Thank you for using my plugin.

Unfortunately, html tags are not allowed in the content property. My plugin draws texts in the canvas element. So, your have to define text objects for each character you want to change the font. Sorry for inconvenience.

**Comment by keijiota** [comment]
I see. No worries. It is still very convenience plugins! Thanks for the feedback. 

Keiji
