### ISSUE TITLE
Laptop and mobile phone compatibility

### ISSUE THREAD

**Issue by Jessica-Schulz** [kurokida/jspsych-psychophysics#48]
Hello @kurokida,

Thank you very much for your plugin - it is very useful! 

I am using jspsych-psychophysics2.js for an online experiment, and was wondering if there is a way to make it compatible with both laptop and mobile phones? So far I’ve programmed it using keyboard responses, but that doesn’t work on mobile phones. Is it possible to make the experiment work on both a laptop and a mobile phone (e.g. by using keyboard response on a laptop and touch screen response on a mobile phone)? If I use button response, I imagine it would be clicking a button with the mouse on a laptop and touching it on a mobile phone? 

I am collecting accuracy and reaction time data.

Thank you very much!

Kind regards,
Jessica

**Comment by kurokida** [comment]
Thank you for using my plugin.

Your understading that the button response should be adopted in your case is correct, but the accuracy of the response time would be not so good especially for the mouse on a laptop. As far as I know, there is no compatible way if you use jsPsych.

My friend @tpronk is familiar with this theme, and they might have a good idea. But they are famililar with PsychoPy more than jsPsych. Thomas, if you don't mind, could you share your opinion?

Best regards,
Daiichiro

**Comment by Jessica-Schulz** [comment]
Thank you very much for your very helpful reply - that sounds great! I was just wondering, do you mean that the accuracy of the response time might be not so good because people need to first "move" the mouse/cursor to the right button before they click?

**Comment by kurokida** [comment]
Yes, it is. The time it takes to move the mouse will have an unfavorable effect on reaction time.

I made [a demo code for touching devices.](https://github.com/kurokida/jspsych-psychophysics/blob/master/psychophysics-demos/touch_to_end.html). In this program, you can press any keys and touch the screen to finish the psychophysics trial.

You can actually [run this program on my website](https://www.psycho.hes.kyushu-u.ac.jp/~kurokid/smartphone/psychophysics-demos/touch_to_end.html).

I hope this works fine.

Best regards,
Daiichiro

**Comment by Jessica-Schulz** [comment]
Hi Daiichiro, 

That is great - thank you very much for your help!

Kind regards,
Jessica
