### ISSUE TITLE
Multiple and diverse text entries showing at the same time

### ISSUE THREAD

**Issue by GaiaCo** [kurokida/jspsych-psychophysics#6]
Hello, 
I am using the psychophysics plug in in order to show two texts at the same time but would like to vary the text in each trial, choosing from a list of possibilities. For the moment I tried using the jsPsych.timetableVariable function but the plug in cannot fetch the text. 

![Cattura](https://user-images.githubusercontent.com/73835823/97878308-c4a05b80-1d1e-11eb-828c-342922492ded.JPG)

The error message is "you have to specify the content of texts". Is this possible with this plug in? 
Thank you, I am really new to this and appreciate any help 
Best, 
Gaia

**Comment by kurokida** [comment]
Thank you for using my plugin!

As for your question, here's an answer that might help
https://github.com/jspsych/jsPsych/discussions/1031#discussioncomment-76667

You have to specify the timelineVariable in the top-level parameter.
That is, you can write as follows:

```javascript

stimuli: [jsPsych.timelineVariable('answer_LEFT')],

```
In additionm the answer_LEFT object needs to be specified without a timelineVariable.

**Comment by kurokida** [comment]
Did you solve the problem?

My earlier response may not have been appropriate.

Please see the [how_to_timeline_variables.txt](https://github.com/kurokida/jspsych-psychophysics/files/5509594/how_to_timeline_variables.txt)

Please change the extension of this file from txt to html, and save it in the demos folder and it should work properly.
